- name: Adds percona key
  apt_key:
    keyserver: keys.gnupg.net
    id: "{{ item }}"
    state: present
  with_items:
    - E1E2CD202D607DAF
    - 1C4CBDCDCD2EFD2A
    - 9334A25F8507EFA5
    - 9E003FA64CAC6D72
  tags: ["pxc:keys"]

- name: Adds percona repositories
  apt_repository:
    repo: 'deb http://repo.percona.com/apt {{ ansible_distribution_release }} main'
    state: present

- name: Installs proxysql
  apt:
    pkg: proxysql
    state: present

- name: Installs mysql-common & client
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - mysql-common
    - mysql-client

- name: Configures proxysql
  template:
    src: proxysql.cnf.j2
    dest: /etc/proxysql.cnf
    mode: 0644
    backup: yes
  notify: Restart proxysql

- name: Creates log dir
  file:
    path: /var/log/proxysql/
    state: directory

- name: Adds logrotate
  template:
    src: proxysql.logrotate.conf.j2
    dest: /etc/logrotate.d/proxysql
    mode: 0644

