- name: Grabs proxysql
  get_url:
    url: https://github.com/sysown/proxysql/releases/download/v{{ proxysql_version }}/proxysql_{{ proxysql_version }}-ubuntu16_amd64.deb
    dest: /tmp/proxysql_{{ proxysql_version }}-ubuntu16_amd64.deb

- name: Installs proxysql
  apt:
    deb: /tmp/proxysql_{{ proxysql_version }}-ubuntu16_amd64.deb

- name: Installs mysql-commong
  apt:
    pkg: mysql-common
    state: present

- name: Configures proxysql
  template:
    src: proxysql.cnf.j2
    dest: /etc/proxysql.cnf
    mode: 0644
    backup: yes
  notify: Restart proxysql
